language: node_js

before_script:
  - sudo apt-get update
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install php5 -y
  - sudo apt-get install gcc-multilib g++-multilib -y  # for hxcpp
  - sudo apt-get install mono-devel mono-mcs -y        # for hxcs
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp
  - haxelib install nodejs
  - haxelib install hxjava
  - haxelib install hxcs

script:
  - haxe -main Test -cp test -debug --interp
  - haxe -main Test -cp test -debug -cpp bin && ./bin/Test-debug
  - haxe -main Test -cp test -debug -php bin && php bin/index.php
  - haxe -main Test -cp test -debug -neko bin/Test.n && neko bin/Test.n
  - haxe -main Test -cp test -debug -js bin/Test.js -lib nodejs && node bin/Test.js
  - haxe -main Test -cp test -debug -java bin && java -jar bin/Test-Debug.jar
  - haxe -main Test -cp test -debug -cs bin && mono bin/bin/Test-Debug.exe