language: haxe

matrix:
  include:
    - haxe: "3.1.3"
      install:
        - sudo apt-get install php5 -qq
        - sudo apt-get install mono-devel mono-mcs -qq
        - sudo apt-get install python3 -qq
        - yes | haxelib install hxcpp
        - yes | haxelib install hxjava
        - yes | haxelib install hxcs
        - yes | haxelib install nodejs
        - yes | haxelib install tink_macro
        - haxelib list

    - haxe: development
      install:
        - sudo apt-get install php5 -qq
        - sudo apt-get install mono-devel mono-mcs -qq
        - sudo apt-get install python3 -qq

        # install and rebuild hxcpp
        - haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        - cd $(haxelib path hxcpp | head -1)tools/hxcpp && haxe compile.hxml
        - cd $(haxelib path hxcpp | head -1)project && neko build.n linux-m64
        - cd $TRAVIS_BUILD_DIR

        - haxelib git hxjava https://github.com/HaxeFoundation/hxjava.git
        - haxelib git hxcs https://github.com/HaxeFoundation/hxcs.git
        - yes | haxelib install nodejs
        - yes | haxelib install tink_macro

        - haxelib list
  allow_failures:
    - haxe: development

script:
  - haxe -main Test -cp test -lib tink_macro -debug --interp
  - haxe -main Test -cp test -lib tink_macro -debug -cpp bin/cpp && ./bin/cpp/Test-debug
  - haxe -main Test -cp test -lib tink_macro -debug -php bin/php && php bin/php/index.php
  - haxe -main Test -cp test -lib tink_macro -debug -neko bin/Test.n && neko bin/Test.n
  - haxe -main Test -cp test -lib tink_macro -debug -js bin/Test.js -lib nodejs && node bin/Test.js
  - haxe -main Test -cp test -lib tink_macro -debug -java bin/java && java -jar bin/java/Test-Debug.jar
  - haxe -main Test -cp test -lib tink_macro -debug -cs bin/cs && mono bin/cs/bin/Test-Debug.exe
  - haxe -main Test -cp test -lib tink_macro -debug -swf bin/Test.swf
  - haxe -main Test -cp test -lib tink_macro -debug -as3 bin/as3
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ]; then
    haxe -main Test -cp test -lib tink_macro -debug -python bin/Test.py && python3 bin/Test.py;
    fi