language: node_js

before_script:
  - sudo apt-get update
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install php5 -y
  - sudo apt-get install gcc-multilib g++-multilib -y  # for hxcpp
  - sudo apt-get install mono-devel mono-mcs -y        # for hxcs
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp
  - haxelib install nodejs
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib install tink_macro

script:
  - haxe -main Test -cp test -lib tink_macro -debug --interp
  - haxe -main Test -cp test -lib tink_macro -debug -cpp bin/cpp && ./bin/cpp/Test-debug
  - haxe -main Test -cp test -lib tink_macro -debug -php bin/php && php bin/php/index.php
  - haxe -main Test -cp test -lib tink_macro -debug -neko bin/Test.n && neko bin/Test.n
  - haxe -main Test -cp test -lib tink_macro -debug -js bin/Test.js -lib nodejs && node bin/Test.js
  - haxe -main Test -cp test -lib tink_macro -debug -java bin/java && java -jar bin/java/Test-Debug.jar
  - haxe -main Test -cp test -lib tink_macro -debug -cs bin/cs && mono bin/cs/bin/Test-Debug.exe
  # - haxe -main Test -cp test -lib tink_macro -debug -python bin/Test.py && python3 bin/Test.py
  - haxe -main Test -cp test -lib tink_macro -debug -swf bin/Test.swf
  - haxe -main Test -cp test -lib tink_macro -debug -as3 bin/as3