language: haxe

sudo: false
dist: trusty
addons:
  apt:
    packages:
      - python3
      - php5-cli
      - mono-devel
      - mono-mcs

matrix:
  include:
    - haxe: "3.2.1"
      install:
        - yes | haxelib install hxcpp
        - yes | haxelib install hxjava
        - yes | haxelib install hxcs
        - yes | haxelib install nodejs
        - yes | haxelib install tink_macro
        - haxelib list

    - haxe: "3.4.0"
      install:
        - yes | haxelib install hxcpp
        - yes | haxelib install hxjava
        - yes | haxelib install hxcs
        - yes | haxelib install nodejs
        - yes | haxelib install tink_macro
        - haxelib list

    - haxe: development
      install:
        # install and rebuild hxcpp
        - haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        - cd $(haxelib path hxcpp | head -1)tools/hxcpp && haxe compile.hxml
        - cd $(haxelib path hxcpp | head -1)project && neko build.n linux-m64
        - cd $TRAVIS_BUILD_DIR
        # install various haxelibs
        - haxelib git hxjava https://github.com/HaxeFoundation/hxjava.git
        - haxelib git hxcs https://github.com/HaxeFoundation/hxcs.git
        - yes | haxelib install nodejs
        - yes | haxelib install tink_macro
        - haxelib list
  allow_failures:
    - haxe: development

script:
  - haxelib dev hxAnonCls $TRAVIS_BUILD_DIR
  - haxe build.hxml
  - haxe test.hxml # --interp
  - haxe -main Test -cp test -lib tink_macro -debug -cpp bin/cpp && ./bin/cpp/Test-debug
  - haxe -main Test -cp test -lib tink_macro -debug -php bin/php && php bin/php/index.php
  - haxe -main Test -cp test -lib tink_macro -debug -neko bin/Test.n && neko bin/Test.n
  - haxe -main Test -cp test -lib tink_macro -debug -js bin/Test.js -lib nodejs && node bin/Test.js
  - haxe -main Test -cp test -lib tink_macro -debug -java bin/java && java -jar bin/java/Test-Debug.jar
  - haxe -main Test -cp test -lib tink_macro -debug -cs bin/cs && mono bin/cs/bin/Test-Debug.exe
  - haxe -main Test -cp test -lib tink_macro -debug -swf bin/Test.swf
  - haxe -main Test -cp test -lib tink_macro -debug -as3 bin/as3
  - if [ "${TRAVIS_HAXE_VERSION}" != "3.2.1" ]; then
      haxe -main Test -cp test -lib tink_macro -debug -python bin/Test.py && python3 bin/Test.py;
      haxe -main Test -cp test -lib tink_macro -debug --interp --macro "hxAnonCls.Macros.buildAll()";
    fi